[package]
name = "connect"
version = "0.1.0"
authors = ["Yuval Kohavi <yuval.kohavi@gmail.com>"]

[dependencies]
libc = "0.2.0"
log = "0.3"
env_logger = "0.3"

num = "0.1"
palette = "0.2"

tk-opc = "0.1"

bit-set = "0.4.0"
rosc = "~0.1"
bitflags = "0.8"


serial = "0.3"

clap = "2.23.3"